version: "3"

services:
  apisix:
    image: apache/apisix:2.15.0-debian
    restart: always
    environment:
      NGX_LUA_REQUEST_TIME_VAR_NAME: apisix_request_time_us
    volumes:
      - ./config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ../../ld.so.preload:/etc/ld.so.preload:ro
      - ../../ngx_lua_request_time.so:/opt/ngx-lua-request-time/ngx_lua_request_time.so:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
